[package]
name = "calcite"
version = "0.2.1"
edition = "2024"
publish = false

[dependencies]
ankha = { version = "0.2", path = "../../crates/ankha" }
intuicio-data = "0.46"
intuicio-core = "0.46"
intuicio-derive = "0.46"
intuicio-parser = "0.46"
intuicio-backend-vm = "0.46"
